import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF9EC',
  },
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 18 : 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8E2D6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerCopy: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#465F4D',
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 14,
    color: '#7A6B56',
  },
  deleteButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF1EA',
    borderWidth: 1,
    borderColor: '#F0B8A7',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 16,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#8CA694',
    backgroundColor: '#FFFFFF',
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 8,
    backgroundColor: '#F7EDD7',
  },
  avatarPlaceholder: {
    width: 92,
    height: 92,
    borderRadius: 8,
    backgroundColor: '#F7EDD7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCopy: {
    flex: 1,
    marginLeft: 14,
  },
  petName: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5A4D3B',
    marginBottom: 6,
  },
  petMeta: {
    fontSize: 14,
    color: '#5A4D3B',
    marginBottom: 3,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8E2D6',
    borderRadius: 24,
    padding: 4,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButton: {
    backgroundColor: '#F4B35A',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#465F4D',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  tabContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 18,
  },
  infoItem: {
    width: '48%',
    minHeight: 76,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#7A6B56',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#465F4D',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#465F4D',
    marginBottom: 10,
  },
  notesBox: {
    borderWidth: 1,
    borderColor: '#D8E2D6',
    borderRadius: 8,
    padding: 14,
    backgroundColor: '#FFFFFF',
    marginBottom: 30,
  },
  notesText: {
    fontSize: 14,
    color: '#5A4D3B',
    lineHeight: 21,
  },
  vaccineCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#D8E2D6',
  },
  vaccineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  vaccineNameWrap: {
    flex: 1,
  },
  vaccineLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#7A6B56',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  vaccineName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#465F4D',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 5,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '800',
  },
  divider: {
    height: 1,
    backgroundColor: '#E9E0D5',
    marginVertical: 12,
  },
  vaccineDates: {
    flexDirection: 'row',
    gap: 12,
  },
  dateCol: {
    flex: 1,
  },
  dateValue: {
    fontSize: 14,
    fontWeight: '800',
    color: '#465F4D',
  },
  appointmentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#D8E2D6',
  },
  appointmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appointmentIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFF3E6',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  appointmentCopy: {
    flex: 1,
    paddingRight: 8,
  },
  appointmentTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#465F4D',
    marginBottom: 4,
  },
  appointmentTime: {
    fontSize: 13,
    color: '#7A6B56',
    lineHeight: 18,
  },
  appointmentStatus: {
    borderRadius: 16,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  appointmentStatusText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#465F4D',
  },
  appointmentNote: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E9E0D5',
    color: '#5A4D3B',
    lineHeight: 20,
  },
  footerActions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'android' ? 18 : 12,
    backgroundColor: '#FFF9EC',
  },
  editButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  editButtonText: {
    color: '#465F4D',
    fontWeight: '900',
    fontSize: 15,
  },
  bookButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 24,
    backgroundColor: '#F4B35A',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  bookButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    padding: 18,
  },
  editModal: {
    maxHeight: '90%',
    backgroundColor: '#FFF9EC',
    borderRadius: 18,
    padding: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#465F4D',
  },
  avatarPicker: {
    alignSelf: 'center',
    marginBottom: 18,
  },
  editAvatarPreview: {
    width: 112,
    height: 112,
    borderRadius: 18,
    backgroundColor: '#F7EDD7',
  },
  editAvatarPlaceholder: {
    width: 112,
    height: 112,
    borderRadius: 18,
    backgroundColor: '#F7EDD7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F4B35A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFF9EC',
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#7A6B56',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    color: '#465F4D',
    fontSize: 15,
    marginBottom: 12,
  },
  notesInput: {
    minHeight: 92,
    paddingTop: 12,
  },
  sexToggle: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
  },
  sexToggleButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sexToggleButtonActive: {
    backgroundColor: '#F4B35A',
  },
  sexToggleText: {
    color: '#465F4D',
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  sexToggleTextActive: {
    color: '#FFFFFF',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#465F4D',
    fontWeight: '900',
  },
  applyButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 22,
    backgroundColor: '#F4B35A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  errorBox: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0B8A7',
    backgroundColor: '#FFF1EA',
  },
  errorText: {
    color: '#B8472B',
    fontWeight: '700',
    textAlign: 'center',
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyPanel: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
  },
  emptyTitle: {
    marginTop: 10,
    fontSize: 16,
    fontWeight: '900',
    color: '#465F4D',
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 6,
    fontSize: 14,
    color: '#7A6B56',
    textAlign: 'center',
    lineHeight: 20,
  },
});
