import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF9EC',
  },
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 36 : 12,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8E2D6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#465F4D',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#7A6B56',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  previewCard: {
    backgroundColor: '#F7EDD7',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#8CA694',
    padding: 18,
    alignItems: 'center',
    marginBottom: 16,
  },
  previewImage: {
    width: 112,
    height: 112,
    borderRadius: 18,
    backgroundColor: '#F7EDD7',
  },
  previewPlaceholder: {
    width: 112,
    height: 112,
    borderRadius: 18,
    backgroundColor: '#FFF9EC',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9D5CB',
  },
  avatarPicker: {
    alignSelf: 'center',
    marginBottom: 12,
  },
  avatarEditBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F4B35A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFF9EC',
  },
  previewName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#5A4D3B',
  },
  previewDetail: {
    marginTop: 4,
    fontSize: 14,
    color: '#5A4D3B',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#D8E2D6',
    padding: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#465F4D',
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#7A6B56',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 46,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#465F4D',
    marginBottom: 12,
  },
  notesInput: {
    minHeight: 92,
    paddingTop: 12,
  },
  sexToggle: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D8E2D6',
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
  },
  sexToggleButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sexToggleButtonActive: {
    backgroundColor: '#F4B35A',
  },
  sexToggleText: {
    color: '#465F4D',
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  sexToggleTextActive: {
    color: '#FFFFFF',
  },
  saveButton: {
    marginTop: 16,
    backgroundColor: '#F4B35A',
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
    elevation: 4,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});
