import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF9EC',
  },
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 36 : 12,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D8E2D6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#465F4D',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#7A6B56',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  previewCard: {
    backgroundColor: '#F7EDD7',
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: '#8CA694',
    padding: 18,
    alignItems: 'center',
    marginBottom: 16,
  },
  previewImage: {
    width: 120,
    height: 120,
    borderRadius: 28,
    marginBottom: 12,
  },
  previewPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 28,
    marginBottom: 12,
    backgroundColor: '#FFF9EC',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9D5CB',
  },
  previewName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#5A4D3B',
  },
  previewDetail: {
    marginTop: 4,
    fontSize: 14,
    color: '#5A4D3B',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: '#D8E2D6',
    padding: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#465F4D',
    marginBottom: 12,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: '#5A4D3B',
    marginBottom: 8,
    marginTop: 8,
  },
  input: {
    backgroundColor: '#FFF9EC',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#8CA694',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#333333',
  },
  textArea: {
    minHeight: 110,
    paddingTop: 12,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 10,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#FFF9EC',
    borderWidth: 1,
    borderColor: '#D8E2D6',
    alignItems: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#F4B35A',
    borderColor: '#F4B35A',
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#465F4D',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  halfField: {
    flex: 1,
  },
  saveButton: {
    marginTop: 16,
    backgroundColor: '#F4B35A',
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
    elevation: 4,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});