import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFDF7',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 36 : 20,
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  backButton: {
    marginRight: 12,
    padding: 6,
    backgroundColor: '#FFF6E8',
    borderRadius: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#465F4D',
  },
  pageSubtitle: {
    color: '#726E66',
    marginBottom: 16,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: '#EDE6DB',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#6E8A76',
    marginBottom: 12,
  },
  petInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 14,
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3EEE9',
  },
  petAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginRight: 12,
    backgroundColor: '#EEE',
  },
  petAvatarPlaceholder: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginRight: 12,
    backgroundColor: '#FFF3E6',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  petTextBlock: {
    flex: 1,
  },
  petName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#2F3B2E',
  },
  petMeta: {
    marginTop: 4,
    color: '#8A8A8A',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3EEE9',
  },
  infoText: {
    marginLeft: 10,
    color: '#5A4D3B',
    fontWeight: '700',
    flexShrink: 1,
  },
  noteBox: {
    marginTop: 14,
    backgroundColor: '#FFF6E8',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    padding: 14,
  },
  noteLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#835300',
    marginBottom: 8,
  },
  noteText: {
    color: '#5A4D3B',
    lineHeight: 20,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
  },
  backActionButton: {
    flex: 1,
    backgroundColor: '#F0B15A',
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: 'center',
  },
  backActionText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
  },
  confirmActionButton: {
    flex: 1.4,
    backgroundColor: '#6E8A76',
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: 'center',
  },
  confirmActionText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
  },
  disabledButton: {
    opacity: 0.7,
  },
  errorBox: {
    backgroundColor: '#FFF1EA',
    borderColor: '#F0B8A7',
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#B8472B',
    fontWeight: '700',
    textAlign: 'center',
  },
});
