import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9EC',
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
  },
  screenTitle: {
    fontSize: 33,
    fontWeight: '900',
    color: '#4D6453',
    marginBottom: 18,
    letterSpacing: 0.2,
  },
  profileCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    overflow: 'hidden',
    marginBottom: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  profileHeaderSection: {
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 22,
    backgroundColor: '#FFF6E8',
  },
  avatarContainer: {
    alignItems: 'center',
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    backgroundColor: '#F7EDD7',
  },
  headerName: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 12,
    color: '#2F3B2E',
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderColor: '#E8DDCF',
  },
  infoRow: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE5D8',
  },
  lastInfoRow: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  label: {
    fontSize: 15,
    fontWeight: '700',
    color: '#7D4600',
    marginBottom: 4,
  },
  value: {
    fontSize: 15,
    color: '#2F3B2E',
    lineHeight: 20,
  },
  buttonEdit: {
    flexDirection: 'row',
    backgroundColor: '#465F4D',
    paddingVertical: 14,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  buttonEditText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#FFFFFF',
    fontWeight: '400',

  },
  button: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8DDCF',
  },
  buttonText: {
    fontSize: 16,
    marginLeft: 8,
    color: '#333',
    fontWeight: '400',
  },
});
