import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFDF7' },
  container: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 40 },
  headerTitle: { fontSize: 28, fontWeight: '900', color: '#465F4D' },
  headerSubtitle: { color: '#726E66', marginTop: 6, marginBottom: 18 },

  tabRow: { flexDirection: 'row', marginBottom: 18 },
  tabWrapper: {
    marginBottom: 18,
    padding: 6,
    backgroundColor: '#FFF6E8',
    borderRadius: 30,
  },
  tabInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    flexWrap: 'nowrap',
  },
  tabPill: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 0,
    flexShrink: 1,
    margin: 4,
    flexBasis: '35%',
    minWidth: 0,
  },
  tabPillWide: {
    paddingHorizontal: 24,
    flexGrow: 0,
    flexShrink: 1,
    margin: 4,
    flexBasis: '65%',
    minWidth: 0,
  },
  tabPillSpacing: {
    marginRight: 8,
  },
  tabPillActive: {
    backgroundColor: '#F0B15A',
  },
  tabPillInactive: {
    backgroundColor: '#FFF6F3',
  },
  tabPillText: {
    fontWeight: '700',
    fontSize: 14,
  },
  tabPillActiveText: { color: '#FFFFFF' },
  tabPillInactiveText: { color: '#6B4B2B' },

  appointmentCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 14, marginBottom: 16, shadowColor: '#000', shadowOpacity: 0.05, shadowOffset: { width: 0, height: 2 }, elevation: 3, overflow: 'hidden' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  petRow: { flexDirection: 'row', alignItems: 'center' },
  petAvatar: { width: 56, height: 56, borderRadius: 28, marginRight: 12, backgroundColor: '#EEE' },
  petName: { fontWeight: '700', color: '#2F3B2E', fontSize: 16 },
  petService: { color: '#8A8A8A', fontSize: 12 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  statusText: { color: '#6B6B6B', fontWeight: '700', fontSize: 12 },

  cardBody: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  cardBodyRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, flexWrap: 'nowrap' },
  infoCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D8CDBF',
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginRight: 8,
    minWidth: 0,
    marginBottom: 0,
  },
  iconArea: {
    flex: 3,
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 20,
  },
  innerDivider: {
    width: 3,
    backgroundColor: '#D8CDBF',
    marginHorizontal: 0,
    alignSelf: 'stretch',
    height: '100%',
  },
  infoCellRight: { marginRight: 0, marginLeft: 8 },
  iconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFF3E6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    marginRight: 0,
  },
  infoCellContent: { flex: 7, paddingVertical: 12, paddingLeft: 20 },
  infoLabel: { fontSize: 10, color: '#7A6B4A' },
  infoValue: { fontSize: 12, color: '#2F3B2E', marginTop: 4, fontWeight: '700' },

  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  viewButton: { backgroundColor: '#F0B15A', paddingVertical: 14, paddingHorizontal: 28, borderRadius: 28, minWidth: 160, alignItems: 'center' },
  viewButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  cancelButton: { backgroundColor: '#FFFFFF', borderColor: '#D34D3D', borderWidth: 1, paddingVertical: 10, paddingHorizontal: 16, borderRadius: 18, alignItems: 'center' },
  cancelButtonText: { color: '#D34D3D', fontWeight: '700' },

  divider: { height: 1, backgroundColor: '#F3EEE9', marginVertical: 12 },

  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    backgroundColor: '#F0B15A',
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#6E8A76',
  },
});
