import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFDF7' },
  container: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 40 },
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  backButton: { marginRight: 12, padding: 6 },
  headerTitle: { fontSize: 22, fontWeight: '900', color: '#465F4D' },
  topCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, marginBottom: 18 },
  topRow: { flexDirection: 'row', alignItems: 'center' },
  petAvatarPlaceholder: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#EEE', marginRight: 12 },
  topInfo: { flex: 1 },
  smallLabel: { color: '#835300', marginBottom: 8, fontWeight: '800' },
  petNameLarge: { fontSize: 16, fontWeight: '800', color: '#2F3B2E' },
  petMeta: { color: '#8A8A8A', marginTop: 4 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, alignSelf: 'flex-start' },
  statusText: { color: '#6B6B6B', fontWeight: '700' },
  topHeaderRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
  topIconCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFF3E6', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#F0D7B0', marginRight: 12 },
  topIdStatus: { flex: 1 },
  statusRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  topDivider: { height: 1, backgroundColor: '#F3EEE9', marginVertical: 12 },

  detailsCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 0, borderWidth: 1, borderColor: '#EDE6DB' , marginBottom: 18, overflow: 'hidden' },
  rowItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: '#F3EEE9', backgroundColor: '#FFFFFF' },
  rowLeft: { flexDirection: 'row', alignItems: 'center' },
  iconBox: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#FFF3E6', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#F0D7B0', marginRight: 12 },
  rowLabel: { color: '#835300', fontSize: 14, fontWeight: '800' },
  rowValue: { color: '#2F3B2E', fontWeight: '700', flexShrink: 1, textAlign: 'right' },
  notePreviewWrapper: { flex: 1, maxWidth: '50%' },
  rowValueNote: { color: '#2F3B2E', fontWeight: '700', textAlign: 'left', flexShrink: 1 },

  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#EDE6DB',
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#2F3B2E',
    fontSize: 16,
    fontWeight: '900',
  },
  inlineState: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  inlineStateText: {
    color: '#6E8A76',
    fontWeight: '700',
    marginLeft: 8,
  },
  emptySectionText: {
    color: '#7A6B56',
    fontWeight: '700',
    lineHeight: 20,
  },
  prescriptionItem: {
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3EEE9',
  },
  prescriptionTitle: {
    color: '#465F4D',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 6,
  },
  prescriptionMeta: {
    color: '#5A4D3B',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
  },
  actionRow: { marginTop: 6, alignItems: 'center' },
  cancelCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 12, borderWidth: 1, borderColor: '#F3E9E6', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cancelInfo: { flex: 1, paddingRight: 12 },
  cancelTitle: { color: '#2F3B2E', fontWeight: '700', marginBottom: 6 },
  cancelNote: { color: '#8A8A8A', fontSize: 12 },
  cancelPrimaryButton: { backgroundColor: '#FFFFFF', borderColor: '#D34D3D', borderWidth: 2, paddingVertical: 10, paddingHorizontal: 18, borderRadius: 18 },
  cancelPrimaryText: { color: '#D34D3D', fontWeight: '900' },
  disabledButton: { opacity: 0.7 },

  empty: { color: '#8A8A8A' },
  centerState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  errorBox: { backgroundColor: '#FFF1EA', borderColor: '#F0B8A7', borderWidth: 1, borderRadius: 16, padding: 12, marginBottom: 16 },
  errorText: { color: '#B8472B', fontWeight: '700', textAlign: 'center' },
  rescheduleCard: { backgroundColor: '#6E8A76', borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center' },
  rescheduleTitle: { color: '#FFFFFF', fontWeight: '800', marginBottom: 6, fontSize: 16 },
  rescheduleText: { color: '#F3F7F5', maxWidth: 200 },
  rescheduleButton: { backgroundColor: '#FFFFFF', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 14 },
  rescheduleButtonText: { color: '#6E8A76', fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', backgroundColor: '#FFFFFF', borderRadius: 14, padding: 18 },
  modalTitle: { fontWeight: '800', fontSize: 16, color: '#2F3B2E', marginBottom: 8 },
  modalText: { color: '#3A3A3A', fontSize: 14, marginBottom: 16 },
  modalCloseButton: { alignSelf: 'flex-end', backgroundColor: '#F0B15A', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12 },
  modalCloseText: { color: '#fff', fontWeight: '700' },
});
