import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFDF7',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 36 : 20,
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  backButton: {
    marginRight: 12,
    padding: 6,
    backgroundColor: '#FFF6E8',
    borderRadius: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#465F4D',
  },
  headerSubtitle: {
    color: '#726E66',
    marginTop: 6,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EEE4D6',
  },
  heroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: '#FFF3E6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    borderWidth: 1,
    borderColor: '#F0D7B0',
  },
  heroTextWrap: {
    flex: 1,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#465F4D',
    marginBottom: 4,
  },
  heroDescription: {
    color: '#726E66',
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: '#FFF6E8',
    borderRadius: 24,
    padding: 14,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#6E8A76',
    marginBottom: 12,
  },
  petName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2F3B2E',
  },
  petMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#8A8A8A',
  },
  selectionDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#C9D5CB',
    backgroundColor: '#FFFFFF',
  },
  selectionDotActive: {
    borderColor: '#F0B15A',
    backgroundColor: '#F0B15A',
  },
  servicePicker: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  servicePickerLeft: {
    flex: 1,
  },
  servicePickerLabel: {
    color: '#8A8A8A',
    fontSize: 12,
    marginBottom: 4,
    fontWeight: '700',
  },
  servicePickerValue: {
    fontWeight: '700',
    color: '#5A4D3B',
    fontSize: 15,
  },
  petPickerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EEE',
    marginLeft: 12,
  },
  petPickerAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF3E6',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    marginLeft: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateText: {
    marginLeft: 10,
    color: '#5A4D3B',
    fontWeight: '700',
  },
  dateTextInput: {
    flex: 1,
    marginLeft: 10,
    color: '#5A4D3B',
    fontWeight: '700',
    paddingVertical: 0,
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  timeChip: {
    minWidth: 64,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8DDCF',
    alignItems: 'center',
  },
  timeChipActive: {
    backgroundColor: '#F0B15A',
    borderColor: '#F0B15A',
  },
  timeText: {
    color: '#5A4D3B',
    fontWeight: '700',
  },
  timeTextActive: {
    color: '#FFFFFF',
  },
  noteInput: {
    minHeight: 120,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#333333',
  },
  nextButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#F0B15A',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
    elevation: 4,
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E8DDCF',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#465F4D',
  },
  modalServiceItem: {
    backgroundColor: '#FFF6E8',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    marginBottom: 10,
  },
  modalServiceItemActive: {
    backgroundColor: '#F0B15A',
    borderColor: '#F0B15A',
  },
  modalServiceText: {
    fontWeight: '800',
    color: '#5A4D3B',
  },
  modalServiceTextActive: {
    color: '#FFFFFF',
  },
  modalPetItem: {
    backgroundColor: '#FFF6E8',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E8DDCF',
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalPetItemActive: {
    backgroundColor: '#FFF9EC',
    borderColor: '#F0B15A',
  },
  modalPetAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#EEE',
  },
  modalPetAvatarPlaceholder: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFF3E6',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalPetTextWrap: {
    flex: 1,
    marginLeft: 10,
  },
  modalPetName: {
    fontWeight: '800',
    color: '#2F3B2E',
    fontSize: 14,
  },
  modalPetMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#8A8A8A',
  },
  errorBox: {
    backgroundColor: '#FFF1EA',
    borderColor: '#F0B8A7',
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#B8472B',
    fontWeight: '700',
    textAlign: 'center',
  },
  centerState: {
    minHeight: 220,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
