import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF9EC',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 36 : 20,
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  backButton: {
    marginRight: 12,
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8DDCF',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#465F4D',
  },
  emptyText: {
    color: '#7A6B56',
    marginTop: 10,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8DDCF',
    marginBottom: 16,
  },
  heroIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 24,
    backgroundColor: '#FFF3E6',
    borderWidth: 1,
    borderColor: '#F0D7B0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  heroTextBlock: {
    flex: 1,
  },
  heroCategory: {
    fontSize: 12,
    fontWeight: '800',
    color: '#7D4600',
    marginBottom: 4,
  },
  heroName: {
    fontSize: 22,
    fontWeight: '900',
    color: '#2F3B2E',
    marginBottom: 6,
  },
  heroDescription: {
    color: '#6E6E6E',
    lineHeight: 20,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8DDCF',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3EEE9',
  },
  infoLabel: {
    color: '#7A6B56',
    fontWeight: '700',
  },
  infoValue: {
    color: '#2F3B2E',
    fontWeight: '800',
  },
  noteCard: {
    backgroundColor: '#FFF6E8',
    borderRadius: 24,
    padding: 16,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#E8DDCF',
  },
  noteTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#465F4D',
    marginBottom: 8,
  },
  noteText: {
    color: '#5A4D3B',
    lineHeight: 20,
  },
  bookButton: {
    backgroundColor: '#F0B15A',
    borderRadius: 24,
    paddingVertical: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 4,
  },
  bookButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
  },
});